version: '3.4'

networks:
  hotel-booking-dev:
    driver: bridge

services:
  apigateway:
    container_name: "api-gateway"
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - hotel-booking-dev
    depends_on:
      - userservice.api
      - bookingservice.api
      - hotelservice.api

  hotelservice.api:
    container_name: hotel-service
    build:
      context: .
      dockerfile: src/HotelService/HotelService.API/Dockerfile
    networks:
      - hotel-booking-dev
    depends_on:
      - postgre_db
      - rabbitmq
      - redis

  bookingservice.api:
    container_name: booking-service
    build:
      context: .
      dockerfile: src/BookingService/BookingService.API/Dockerfile
    networks:
      - hotel-booking-dev
    depends_on:
      - mongodb
      - postgre_db
      - rabbitmq

  userservice.api:
    container_name: user-service
    build:
      context: .
      dockerfile: src/UserService/UserService.API/Dockerfile
    networks:
      - hotel-booking-dev
    depends_on:
      - postgre_db

  postgre_db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hotel-service, booking-service, user-service
    ports:
      - "5432:5432"
    networks:
      - hotel-booking-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis-cache
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hotel-booking-dev
    volumes:
      - redis-data:/data

  mongodb:
    container_name: mongo-db
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - hotel-booking-dev
    volumes:
      -  mongo-data:/var/lib/mongo/data

  rabbitmq:
    container_name: rabbitmq-broker
    image: rabbitmq:4.0-management
    hostname: "bookings-queue"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hotel-booking-dev
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mongo-data:
  postgres-data:
  redis-data:
  rabbitmq-data:
