<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="CSharpFunctionalExtensions" Version="3.5.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="Hangfire" Version="1.8.18" />
    <PackageReference Include="Hangfire.Mongo" Version="1.11.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UserService.Infrastructure\UserService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
